// the state argument here is not application state, only the state this reducer is responsible for - that is the state generated by BooksReducer

export default function(state = null, action) {
  switch(action.type) {
    case 'BOOK_SELECTED':
      return action.payload
  }
  return state
}
